[package]
name = "uefi-app"
version = "0.1.0"
authors = ["jonas"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uefi="0.4"
uefi-services="0.2"
log = { version = "0.4.8", default-features = false }